function plotBF(mesh,BF,sponge,nx,ny)
    if ~exist('nx'); nx=1;end
    if ~exist('ny'); ny=1;end
        
    f=figure
    f.Position(3:4)=[800,800];
        i=1;
        PP = mesh.X*0;
        for P = {BF.RHO ,'$\rho$'; ...
                 BF.U   ,'$U$'   ; ...
                 BF.V,'$V$'; ...
                 BF.W,'$W$';  ...
                 BF.T,'$T$'; ...
                 sponge,'$sponge$'; ...
                 BF.MU,'$\mu$'; ...
                 BF.dMUdT,'$\frac{d\mu}{dT}$'; ...
                 BF.d2MUdT2,'$\frac{d^2\mu}{dT^2}$'; ... 
                 mesh.Dy*(BF.W(:)),'$\frac{dW}{dy}$'; ...
                 mesh.Dx*(BF.W(:)),'$\frac{dW}{dx}$'; ...
                 mesh.Dx*(mesh.Dy*BF.W(:)),'$\frac{d^2W}{dydx}$'}'
                PP(:) = P{1}(:);
                subplot(4,3,i)
                    countourfMultiDomain(mesh,PP); 
                    colorbar;
                    cmin = min(PP(:));
                    cmax = max(PP(:));
                    daspect([1,1,1])
                    title(P{2});
                i=i+1;
        end
